### ISSUE TITLE
Add explicit parameter value/type correctness checks

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#329]
### What is the expected enhancement?

Currently algorithm parameters are either not checked for correctness or checked in a few places. Despite we have type hints, users may supply whatever they want values, e.g. `None` where it is not supported. For instance, if a user passes `None` as a lost function an exception like `'NoneType' object has no attribute 'lower'` is raised.

This enhancement request should address this issue and introduce additional type and correctness checks across the module. If a wrong value is passed a friendly message should raised in the exception. I'm open to discuss how such checks can implemented and whether they even required. I'd happy to see if @woodsp-ibm has an opinion on this issue. Perhaps, such things should be implemented similarly across modules/projects.

**Comment by woodsp-ibm** [comment]
If I read the text above correctly you are talking about both values and type - the title has 'parameter value' and if the intent is to span both then maybe drop 'value' from it.

In regards of the attribute error example, you will also get the same at runtime if you pass in some other valid non-None object that does not have an attribute lower. Of course it maybe another type instance you created that conforms to what is needed, and lo and behold just works due to duck-typing. How many places would you want to guard against None at runtime explicitly? Certainly for other values we may want to guard them, and indeed do in many places, where giving some values may not fail but the result is meaningless and a user may not be able to determine this, so we fail early when we know it will be the case. Given your above example, and my extension thereof, you have the error whereby a person with a reasonable understanding of Python will understand/figure out what is going on.

As to whether we want to do it or not, that's another big question I guess! Presently I see type checking mainly occurring in places where a parameter can be a Union of different types that need slightly different processing. In this case there can be an else at the end where any unsupported type being passed is raised as an error. In this case it seems valid. But in general type checking at runtime so far has not been done. It could be a lot of code checking in all the public APIs we have and it seems to go against the grain for duck typing. The type hints were added to allow mypy, or your IDE etc, to highlight mismatches where they can, so you can address things early statically where/if possible.

Whatever is done, if anything, I guess needs to be account for usability, maintainability and the pythonic way of doing things.

**Comment by woodsp-ibm** [comment]
My bad, somehow I hit the close button accidentally! Where is that UI runtime checking when I needed it!

**Comment by manoelmarques** [comment]
Python follows the EAFP principle: https://www.geeksforgeeks.org/eafp-principle-in-python/
Basically, if a parameter is passed incorrectly, throws an exception from the function itself or the runtime. If a function can recover or if more description is needed, then it is ok to validate before hand.
Checking every argument for every function before usage is irregular usage of python but I will leave to @mtreinish to comment further.

**Comment by adekusar-drl** [comment]
Close as won't fix.
