### ISSUE TITLE
A problem with PegasosQSVC function when using decision_function function

### ISSUE THREAD

**Issue by Abdualazem** [Qiskit/qiskit-machine-learning#387]
### Environment

- **Qiskit Machine Learning version**: 0.4.0
- **Python version**: 3.7.1
- **Operating system**: Ubuntu 20.04

### What is happening?

Using the PegasosQSVC example [here](https://qiskit.org/documentation/machine-learning/tutorials/07_pegasos_qsvc.html), and calculating the score using decision_function, I got the following error:

`AttributeError: 'PegasosQSVC' object has no attribute '_sparse'`

### How can we reproduce the issue?

 I use the example provided here https://qiskit.org/documentation/machine-learning/tutorials/07_pegasos_qsvc.html

```python
from qiskit_machine_learning.algorithms import PegasosQSVC

pegasos_qsvc = PegasosQSVC(quantum_kernel=qkernel, C=C, num_steps=tau)
#pegasos_qsvc = PegasosQSVC(quantum_kernel=qkernel)

pegasos_qsvc.fit(train_features, train_labels)

pegasos_score = pegasos_qsvc.score(test_features, test_labels)

y_score_qsvc = pegasos_qsvc.decision_function(test_features) # Just adding this line which is the cause of the problem. 
#y_score_qsvc = pegasos_qsvc.predict(test_features)

print(y_score_qsvc)
print(f"PegasosQSVC classification test score: {pegasos_score}")
```

### What should happen?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_8351/1609182878.py in <module>
      9 pegasos_score = pegasos_qsvc.score(test_features, test_labels)
     10 
---> 11 y_score_qsvc = pegasos_qsvc.decision_function(test_features)
     12 #y_score_qsvc = pegasos_qsvc.predict(test_features)
     13 

~/.anaconda3/envs/qiskit/lib/python3.7/site-packages/sklearn/svm/_base.py in decision_function(self, X)
    754         transformation of ovo decision function.
    755         """
--> 756         dec = self._decision_function(X)
    757         if self.decision_function_shape == "ovr" and len(self.classes_) > 2:
    758             return _ovr_decision_function(dec < 0, -dec, len(self.classes_))

~/.anaconda3/envs/qiskit/lib/python3.7/site-packages/sklearn/svm/_base.py in _decision_function(self, X)
    512         # NOTE: _validate_for_predict contains check for is_fitted
    513         # hence must be placed before any other attributes are used.
--> 514         X = self._validate_for_predict(X)
    515         X = self._compute_kernel(X)
    516 

~/.anaconda3/envs/qiskit/lib/python3.7/site-packages/sklearn/svm/_base.py in _validate_for_predict(self, X)
    599             )
    600 
--> 601         if self._sparse and not sp.isspmatrix(X):
    602             X = sp.csr_matrix(X)
    603         if self._sparse:

AttributeError: 'PegasosQSVC' object has no attribute '_sparse'
```

**Comment by woodsp-ibm** [comment]
The `decision_function` is part of the base SVC code in sklearn. The PegasosQSVC here extends that and overrides some methods like 'fit' but has no implementation of that so it ends up using that of the sklearn code. Now looking at the sklearn SVC fit it sets up this _sparse member when its fit is called. Since that code is not exercised the decision function code ends up failing.

In searching it seems similar to this now quite [old issue in sklearn](https://github.com/scikit-learn/scikit-learn/issues/3601) where that message was seen if the SVC was called ahead of being fit. This is sort of what is happening now with it running the PegasosQSVC fit that is separate as such from the base SVC fit.

This is something that needs to be looked at a bit more to figure what to do about this.

**Comment by Abdualazem** [comment]
In my case, the ``predict()`` function works fine the problem comes when using ``decision_function()``. Unlike the old issue you shared, the error occurs even though the data is fitted in advance.

**Comment by woodsp-ibm** [comment]
'predict' is overriden in the PegasosQSVC whereas `decision_function` is still using the method of the base SVC in sklearn. The data is fitted according to PegasosSVC but the base class fit is not called, hence whatever it does/needs in the base class to support other methods of the base class being called successfully later, like setting this _spare member does not get done. Hence the base class code behaves as if its not been fitted which is why I referenced that issue.

**Comment by Abdualazem** [comment]
Well explained; thanks a lot, @woodsp-ibm. Is there a workaround for this? I'm just avoiding `QSVC`, which works fine, but lacks hyperparameters for tuning like the `PegasosQSVC`.

**Comment by adekusar-drl** [comment]
My two cents here. `PegasosQSVC` has its own fit implementation. That's why `PegasosQSVC` may not support full functionality of `SVC`. Currently, there's no a quick fix for this problem.

On the other hand `QSVC` just wraps `SVC` from SciKit-Learn and expose an additional parameter `quantum_kernel` as a kernel function. So, in terms of hyperparameterization `QSVC` has more options and all `kwargs` options it receives in the constructor it passes to the underlying `SVC`. Thus, `decision_function()` works perfectly fine and you may pass additional parameters, see the snippet, I pass `C` and `max_iter`.
```python
import numpy as np
from qiskit import BasicAer
from qiskit.circuit.library import ZZFeatureMap
from qiskit.utils import algorithm_globals, QuantumInstance
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from qiskit_machine_learning.algorithms import QSVC
from qiskit_machine_learning.kernels import QuantumKernel

algorithm_globals.random_seed = 10598

statevector_simulator = QuantumInstance(
    BasicAer.get_backend("statevector_simulator"),
    shots=1,
    seed_simulator=algorithm_globals.random_seed,
    seed_transpiler=algorithm_globals.random_seed,
)

features, labels = make_blobs(n_samples=20, n_features=2, centers=2, random_state=3, shuffle=True)
features = MinMaxScaler(feature_range=(0, np.pi)).fit_transform(features)

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, train_size=15, shuffle=False)

kernel = QuantumKernel(feature_map=ZZFeatureMap(feature_dimension=2), quantum_instance=statevector_simulator)

qsvc = QSVC(quantum_kernel=kernel, C=0.1, max_iter=10)
qsvc.fit(train_features, train_labels)
print(qsvc.score(test_features, test_labels))
print(qsvc.decision_function(test_features))
```

@gentinettagian for your information.

**Comment by Abdualazem** [comment]
Thanks a lot, @adekusar-drl, for the snippet. I'll fall back to `QSVC` instead of the `PegasosQSVC` for now.

**Comment by gentinettagian** [comment]
Thanks @adekusar-drl for tagging me. I think we should question whether`PegasosQSVC` should really inherit from `SVC`. The class is quite large and the main methods (`fit` and `predict`) are overridden and handled quite differently in `PegasosQSVC`. If we do inherit from `SVC` we should make sure that every method works, or at least raises a `NotImplementedError`. In any case, a `decision_function` method would be easy to implement. This is just the value calculated in `predict` before taking the sign.

**Comment by adekusar-drl** [comment]
@gentinettagian I agree. Perhaps we should revise inheritance considering your work.
