### ISSUE TITLE
Make use of `AerPauliExpectation` for gradients, quantum Fisher information

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#59]
### What is the expected enhancement?
Make sure `AerPauliExpectation` can be used for gradients, QFI, etc

**Comment by Cryoris** [comment]
While the code allows to use AerPauliExpectation, it currently gives wrong results due to a bug in the expectation values if coefficients in the state function are involved -- as is the case for gradients.

**Comment by Cryoris** [comment]
With Qiskit/qiskit-terra#6497 merged, this issue is resolved.

The `AerPauliExpectation` now yields the correct values, see this plot which shows the absolute difference between gradients calculated exactly (using the matrix expectation) again Pauli and AerPauli: 
![image](https://user-images.githubusercontent.com/5978796/123935430-808c5600-d994-11eb-8053-a0dbf69d48e0.png)

and here's a small runtime comparison (not including matrix expectation because that scales way too bad and reaches the 40s mark already for 12 qubits):
![image](https://user-images.githubusercontent.com/5978796/123935730-c9440f00-d994-11eb-8f43-77acb80cdfdd.png)
